export const casteOptions = [
  "96 Kuli Maratha",
  "Agri",
  "Ahir Shimpi",
  "Ahirwal",
  "Anjana (Chaudhari Patel)",
  "Aramari (Gabit)",
  "Arya Vysya",
  "Bairwa",
  "Balai",
  "Banjara",
  "Barai",
  "Bari",
  "Bhavsar (Khatriya)",
  "Bhandari",
  "Bhoi",
  "Bhill",
  "Brahman (Anavil Desai)",
  "Brahman (Audichya Vaidiki)",
  "Brahman Bardai",
  "Brahman Daivadnya",
  "Brahman Deshastha",
  "Brahman Karhade",
  "Brahman Khadayata",
  "Brahman Khedaval",
  "Brahman Kokanastha",
  "Brahman Mevada",
  "Brahman Rajgor",
  "Brahman Rarhi",
  "Brahman Rigvedi",
  "Brahman Saraswat",
  "Brahman Sarua",
  "Brahman Shri Gaud",
  "Brahman Smartha",
  "Brahman Tapodhan",
  "Brahman Valam",
  "Brahman Zalora",
  "CKP",
  "Cash Che Bar",
  "Chambhar",
  "Charan",
  "Deshmukh",
  "Devang Koshthi",
  "Dhanak",
  "Dhangar",
  "Dhor (Kakkayya)",
  "Gabit",
  "Gavandi",
  "Gawali",
  "Ghisadi",
  "Gomantak",
  "Gond",
  "Gondhali",
  "Gurav",
  "Halba Koshti",
  "Holar",
  "Intercaste",
  "Jangam",
  "Jadhav",
  "Jog (Nath)",
  "Julaha",
  "Kalar",
  "Kanakkan Padanna",
  "Kundara",
  "Kasar",
  "Kayastha",
  "Khatik",
  "Kokanastha Maratha",
  "Koli",
  "Koli Mahadev",
  "Konkani",
  "Koshti",
  "Kshatriya",
  "Kshatriya Raju",
  "Kumaoni Rajput",
  "Kumbhar",
  "Kunbi",
  "Kunbi Lonari",
  "Kumbi Maratha",
  "Kurbi Tirali",
  "Leva Patil",
  "Lingayat",
  "Lohar",
  "Madivala (Dhobi)",
  "Mahar",
  "Mair Rajput Swarnakar",
  "Mali",
  "Malvani",
  "Mannan (Velan/Vannan)",
  "Maratha",
  "Maratha Kshatriya",
  "Matang",
  "Meghwal",
  "Nabit",
  "Nhavi",
  "Atari",
  "Other Brahman",
  "Pallan (Devendra Kula Vellunan)",
  "Panan",
  "Paravan (Bharatar)",
  "Parit",
  "Paswan (Dusadh)",
  "Patel",
  "Pathare Prabhu",
  "Patil",
  "Poundra",
  "Pulaya (Cheruman)",
  "Rajput",
  "Ramoshi",
  "Rohit (Chamar)",
  "SC",
  "SKP",
  "ST",
  "Samagar",
  "Sambava",
  "Satnami",
  "Savji",
  "Shipkar",
  "Shimpi (Namdev)",
  "Sonar",
  "Sonkar",
  "Suthar",
  "Swakula Sali",
  "Teli",
  "Thandan",
  "Vadar",
  "Vaishnav",
  "Vaishav Kapol",
  "Vaishnav Khadayata",
  "Vaishva Ladd",
  "Vashnav Modh",
  "Vaishnav Porvad",
  "Vaishnav Vania",
  "Vaishnav Vaniya",
  "Vani",
  "Vaniya",
  "Vanjari",
  "Vyasa",
  "Yadav",
  "Other",
];

export default {};
